$(document).ready(function(){
        $(".carousel").toggle();
    $(".alert").click(function(){
        $(".alert").slideUp("slow");
    });
     $(".testy").click(function(){
        $(".minething").toggle();
         $(".carousel").toggle();
    });
});